# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Cyanbox/curriculum/arch/RISC-V_lab/PPL_CACHE_PLUS_changesize_stage2/ArchTestUtils.srcs/sources_1/ip/Memory_core/Memory_core.xci
# IP: The module: 'Memory_core' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Cyanbox/curriculum/arch/RISC-V_lab/PPL_CACHE_PLUS_changesize_stage2/ArchTestUtils.srcs/sources_1/ip/Memory_core/Memory_core_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Memory_core'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Cyanbox/curriculum/arch/RISC-V_lab/PPL_CACHE_PLUS_changesize_stage2/ArchTestUtils.srcs/sources_1/ip/Memory_core/Memory_core.xci
# IP: The module: 'Memory_core' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Cyanbox/curriculum/arch/RISC-V_lab/PPL_CACHE_PLUS_changesize_stage2/ArchTestUtils.srcs/sources_1/ip/Memory_core/Memory_core_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Memory_core'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
